Mei/add col order
fucusy/dataframe2html pull request #14
Opened 2020-04-24 03:21 UTC by BAIMEI1

the problem the pr solve:
- add colOrder handle logic. if our user does hope that content in a row in order, we can provide this feature.
- make 2D method more reasonable, the user does not have to use a column which is named "row".
uses just need tell us the rowOrderCol name then we will handle it.

2020-04-24 04:09 UTC, fucusy requested changes

2020-04-24 04:09 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +  private def addRowTitle(rowTitle: Option[String])(df: DataFrame): DataFrame = {
A few lines code doesn't worth creating a new function

2020-04-24 04:09 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +                       colOrderCol: Option[String] = None,
To make the logic clear, let's required to have row, col, title columns. 
For our case, we have row, video_position, container_slug.  

We can make our API more flexible when necessary.

2020-04-24 04:09 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +                     colOrderCol: Option[String] = None,
We will assume the data frame is ordered before using the function dataframe2data.

2020-04-24 04:09 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +                     colOrderCol: Option[String] = None,
So, we don't need to update this function

2020-04-24 07:28 UTC, BAIMEI1 commented on src/main/scala/io/github/fucusy/Viz.scala
> +                     colOrderCol: Option[String] = None,
no, dataframe in spark are not in order!! when I try to do 2d method, the video_position did not in order at all. but in fact we need it to keep order. https://dbc-5f2acc18-b29d.cloud.databricks.com/?o=6211501775943445#notebook/2550389456839224/command/2550389456839225
![image](https://user-images.githubusercontent.com/21968023/80186055-f9c94400-863f-11ea-87b6-734c69368657.png)

2020-04-24 07:30 UTC, BAIMEI1 commented on src/main/scala/io/github/fucusy/Viz.scala
> +                       colOrderCol: Option[String] = None,
I think for 2D method we require rowOrderCol is enough, colOrderCol and rowrTitleCol can be empty logically. if users want to show these two fields. they can do that. as long as we can support more, why we do not support it?

2020-04-24 07:34 UTC, BAIMEI1 commented on src/main/scala/io/github/fucusy/Viz.scala
> +  private def addRowTitle(rowTitle: Option[String])(df: DataFrame): DataFrame = {
I just want to separate it from the main logic. it's a relatively independent logic. I think we should create a method by function but not how many lines do they have.

2020-04-24 09:02 UTC, fucusy requested changes
Leave two comments, Others LGTM

2020-04-24 09:02 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +      df.withColumn("row_title", F.row_number.over(Window.orderBy(F.col(df.columns(0)).desc)))
are we setting the default title column to some row number. df.columns(0) could be some unknown column.

Can we do this to simplify the logic:
```
df.withColumn("row_title", F.col(rowTitleCol.getOrElse(rowOrderCol))
```

2020-04-24 09:02 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +      .map(_.getAs[Int](rowOrderCol))
we only have one column here, 
```
.map(_.toString.toInt)
```
should work

2020-04-24 09:21 UTC, BAIMEI1 commented on src/main/scala/io/github/fucusy/Viz.scala
> +      df.withColumn("row_title", F.row_number.over(Window.orderBy(F.col(df.columns(0)).desc)))
got, changed

2020-04-24 09:21 UTC, BAIMEI1 commented on src/main/scala/io/github/fucusy/Viz.scala
> +      .map(_.getAs[Int](rowOrderCol))
no, it did not work
![image](https://user-images.githubusercontent.com/21968023/80196442-0190e480-8650-11ea-8e4d-ce01d7864fc7.png)

2020-04-24 10:32 UTC, fucusy requested changes

2020-04-24 10:32 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +    }
`val addRowTitleDF  = df.withColumn("row_title", F.col(rowTitleCol.getOrElse(rowOrderCol))`

2020-04-24 10:32 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +    val rowTitleColumn: Column = rowTitleCol match {
we don't need this, because rowTitleColumn will be always row_title

2020-04-26 06:49 UTC, fucusy commented
@BAIMEI1 CI Failed

2020-04-26 08:49 UTC, fucusy approved these changes
LGTM

2020-04-26 08:49 UTC, fucusy commented on src/main/scala/io/github/fucusy/Viz.scala
> +    val dropOriginRowTitleColDF = if(rowTitleCol != None){
rowTitleCol.isDefined

2020-04-26 08:52 UTC, merged